### ISSUE TITLE
Proxy EventTarget todo's

### ISSUE THREAD

**Issue by andrieshiemstra** [HiRoFa/quickjs_es_runtime#28]
* [x] addEventListener from rust
* [x] removeEventListener from rust
* [x] dispatchEvent from rust

test todos
* [x] removeEventListener
* [x] dispatch from javascript
* [x] addListener from rust
